name: Deployment Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  SKIP_DEPLOY: ${{ contains(join(github.event.commits.*.message), '#skip') }}
  AUTHOR: ${{ github.event_name == 'push' && github.event.pusher.username || github.event.pull_request.user.login }}
  COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
  
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: End2End Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:8080
      - name: Debug Messages
        env:
          MSGS: ${{ join(github.event.commits.*.message) }}
        run: echo "$MSGS" "${{ github.env.SKIP_DEPLOY }} ${{ github.event_name }}"
      - name: 
      - name: Trigger Deploy
        id: trigger_deploy
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: ${{ github.env.SKIP_DEPLOY == 'false' && github.event_name == 'push' }}
      - name: Notify Deploy
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          text: A new version of Pokedex deployed
          severity: info
          details: to https://full-stack-open-pokedex-s7q2.onrender.com/ by ${{ github.env.AUTHOR }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ steps.trigger_deploy.conclusion == 'success' }}
      - name: Notify Error
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          text: Build failed
          severity: error
          details: commit ${{ github.env.COMMIT_URL }} by ${{ github.env.AUTHOR }} broke the build
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ failure() }}
  tag_release:
    needs: 
      - simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
    if: ${{ github.env.SKIP_DEPLOY == 'false' && github.event_name == 'push' }}
