name: Deployment Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

env:
  SKIP_DEPLOY: ${{ contains(join(github.event.commits.*.message), '#skip') }}
  AUTHOR: ${{ github.event_name == 'push' && github.event.head_commit.author.name || github.event.pull_request.user.login }}
  COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}
  
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: End2End Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:8080
      - name: Trigger Deploy
        id: trigger_deploy
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: ${{ env.SKIP_DEPLOY == 'false' && github.event_name == 'push' }}
      - name: Notify Deploy
        uses: sarisia/actions-status-discord@v1.15.0
        with:
          title: A new version of Pokedex deployed
          status: Success
          color: 0x00ff00
          description: to https://full-stack-open-pokedex-s7q2.onrender.com/ by ${{ env.AUTHOR }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: Github Actions
        if: ${{ steps.trigger_deploy.conclusion == 'success' }}
      - name: Notify Error
        uses: sarisia/actions-status-discord@v1.15.0
        with:
          title: Build failed
          status: Failure
          color: 0xff0000
          description: commit ${{ env.COMMIT_URL }} by ${{ env.AUTHOR }} broke the build
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: Github Actions
        if: ${{ failure() }}
  tag_release:
    needs: 
      - simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
    if: ${{ github.env.SKIP_DEPLOY == 'false' && github.event_name == 'push' }}
